### ISSUE TITLE
zio integration

### ISSUE THREAD

**Issue by vitaliihonta** [itkpi/cakeless#11]
Integrate with scalaz-zio

**Comment by jdegoes** [comment]
Looking forward to this one. 😄

**Comment by vitaliihonta** [comment]
So, we've decided to have `cakeless-kernel`, and 2 separate implementations:
`cakeless-cats` and `cakeless-zio`.
This allows not to have 2 different IO monads in the library.
This also allows not to use additional interop stuff (like `zio-cats` and so on.)

**Comment by vitaliihonta** [comment]
Done :smile:

**Comment by jdegoes** [comment]
Let's chat tomorrow! I got sick today
